[package]
name = "wasm_runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"

[dev-dependencies]
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
tempfile = "3.10.1"
plotters = "0.3.6"

[features]
default = ['wasmgc']
wasm = []
wasmgc = []
