(module
  (type $boxed-i32 (struct (field (mut i32))))
  (func $make
    (param $i i32)
    (result (ref null $boxed-i32))
    (struct.new $boxed-i32 (local.get $i))
  )
  (func $get
    (param $o (ref null $boxed-i32))
    (result i32)
    (struct.get $boxed-i32 0 (local.get $o))
  )
  (func $set
    (param $o (ref null $boxed-i32))
    (param $i i32)
    (struct.set $boxed-i32 0 (local.get $o) (local.get $i))
  )
  (export "make" (func $make))
  (export "get" (func $get))
  (export "set" (func $set))

  (func (export "_start")
    (result i32)
    (local $o (ref null $boxed-i32))
    (local $i i32)
    (local.set $i (i32.const 42))
    (local.set $o (call $make (local.get $i)))
    (local.set $i (call $get (local.get $o)))
    (i32.const 1)
    (local.get $i)
    (i32.add)
    (local.set $i)
    (call $set (local.get $o) (local.get $i))
    (call $get (local.get $o))
  )
)
